window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/23803279-4555db52';
window.___jsl.l=[];
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.gwidget=window.__GOOGLEAPIS.gwidget||{};
window.__GOOGLEAPIS.gwidget.superbatch=false;window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plusone=window.__GOOGLEAPIS.iframes.plusone_m=window.__GOOGLEAPIS.iframes.plusone||{url:':socialhost:/u/:session_index:/_/+1/fastbutton',params:{count:'',size:'',url:''}};window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/u/:session_index:/_/sharebox/dialog"},":socialhost:":"https://apis.google.com","plusone_m":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"chili.entities.starred.insert":{"cache":{"invalidates":["chili.entities.starred","chili.entitiesDefaultAcl"]}},"chili.people.get":true,"chili.entities.get":true,"pos.plusones.delete":true,"chili.entities.starred.delete":true,"chili.entities.list":true,"pos.plusones.get":true,"chili.groups.list":true,"pos.plusones.getDefaultAcl":{"cache":{"enabled":true}},"chili.entities.starred.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"chili.entitiesDefaultAcl.get":true,"chili.entities.starred.list":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"proxy":"https://clients6.google.com/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","jsh":"r;gc/23803279-4555db52","auth":{"useInterimAuth":false}}});var jsloader=window.jsloader||{};
var gapi=window.gapi||{};
(function(){function j(b,c,a){a=l(a).join(b);e.l.length>0&&(a+=c+l(e.l).join(b));return a}function l(b){b.sort();for(var c=1;b[c];)b[c]==b[c-1]?b.splice(c,1):++c;return b}function r(b){if((m||document.readyState)!="loading")return!1;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(b&&(b=b.sync,typeof b!="undefined"))return b;for(var b=!1,c=document.getElementsByTagName("meta"),a=0,d;d=!b&&c[a];++a)"generator"==d.getAttribute("name")&&"blogger"==d.getAttribute("content")&&(b=
!0);return b}function n(b,c,a,d){if(c){if(a){if(e.c)throw"Cannot continue until a pending callback completes.";e.c=a;e.o=1}a=c;if(a.indexOf("..")>=0)a=!1;else if(g==="r")a=a.match(s);else if(g==="m")a=a.match(t);else{var f=a.match(u);if((a=e.m)&&f)var f=f[2],h=f.lastIndexOf(a),a=(h==0||a.charAt(0)=="."||f.charAt(h-1)==".")&&f.length-a.length==h;else a=!1}if(!a)throw"Cannot load url "+c+".";r(d)?document.write('<script src="'+c+'"><\/script>'):(d=document.createElement("script"),d.setAttribute("src",
c),document.getElementsByTagName("head")[0].appendChild(d));e.l.push.apply(e.l,b)}else a&&a()}function o(b,c){g="";e=window.___jsl=window.___jsl||{};h=window.console||window.opera&&window.opera.postError;k=b;m=c;e.l=e.l||[];var a,d=k.match(v)||k.match(w);try{a=d?decodeURIComponent(d[2]):e.h}catch(j){}a&&(a=a.split(";"),g=a.shift(),f=g==="r"?"https://ssl.gstatic.com/webclient/js":g==="m"?e.ms||"https://apis.google.com":a.shift(),i=a.shift(),p=(d=g==="d")&&a.shift()||"gcjs-3p",q=d&&a.shift()||"")}var v=
/\?([^&#]*&)*jsh=([^&#]*)/,w=/#([^&]*&)*jsh=([^&]*)/,s=/^https:\/\/ssl.gstatic.com\/webclient\/js(\/([a-zA-Z0-9_\-\.,:!=]+))*\/([a-zA-Z0-9_\-\.,:!=]+)?$/,t=/^(https?:\/\/[^/]*.google.com(:[0-9]+)?)(\/([a-zA-Z0-9_\-\.,:!=]+))*\/([a-zA-Z0-9_\-\.,:!=]+)?$/,u=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?\//,e,g,f,p,q,i,h,k,m;o(document.location.href);jsloader.load=function(b,c){var a;if(!b||b.length==0)h&&h.warn("Cannot load empty features.");else if(g==="d")a=b,a=(f[f.length-1]=="/"?f.substring(0,f.length-1):
f)+"/"+j(":","!",a),a+=".js?container="+p+"&c=2&jsload=0",i&&(a+="&r="+i),q=="d"&&(a+="&debug=1");else if(g==="r"||g==="f")a=f+"/"+i+"/"+j("__","--",b)+".js";else if(g==="m"||g==="n")a=b.join(",").replace(/\.|-/g,"_","g"),a=f+i.replace("__features__",a);else{var d="Cannot respond for features ["+b.join(",")+"].";h&&h.warn(d)}c=c||{};typeof c==="function"?n(b,a,c):((e.cu=e.cu||[]).push(c.config),d=c.callback,n(b,a,d,c))};jsloader.reinitialize_=function(b,c){o(b,c)}})();
gapi.load=function(a,b){jsloader.load(a.split(":"),b)};
(window.gapi=window.gapi||{}).load=gapi.load;
gapi.load('googleapis.client:plusone', {'callback': window['__bsld']  });